color: '#D2E5FF'
completed: 0
creator: admin
credentials: device
custom_username: ''
description: ''
display_only_failed_nodes: false
failed: 0
has_targets: true
hidden: false
include_link_in_summary: false
initial_payload: {}
jobs:
- Start
- End
- Test Netmiko Prompt Service
- Test netmiko prompts pass
last_modified: '2019-07-19 15:59:10.240134'
mail_recipient: ''
name: Netmiko prompts
notification_header: ''
number_of_retries: 0
number_of_targets: 1
operating_system: ''
positions: {}
push_to_git: false
query_property_type: name
send_notification: false
send_notification_method: mail_feedback_notification
shape: box
size: 40
start_new_connection: false
time_between_retries: 10
type: Workflow
use_workflow_targets: true
vendor: ''
waiting_time: 0
yaql_query: ''
