repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
  -   repo: https://gitlab.com/pycqa/flake8
      rev: master
      hooks:
      -   id: flake8
          args: ['--config=linting/.flake8']
  - repo: https://github.com/prettier/prettier
    sha: 1.12.1
    hooks:
      - id: prettier