branches:
  only:
    - master
    - develop

matrix:
  include:
    - language: python
      python:
        - 3.6
        - 3.7
      install:
        - pip install -r requirements_dev.txt
      script:
        - flake8
        - sudo apt-get update
        - sudo apt-get install google-chrome-stable
        - sudo apt-get install chromium-browser
        - sudo chmod a+x ./tests/chromedriver
        - coverage run --source=./eNMS -m pytest
      after_success:
        - coveralls

    - language: node_js
      node_js: 
        - "node"
      script: 
        - npm run lint