- auto_find_prompt: true
  close_connection: false
  color: '#D2E5FF'
  commands: show vrf
  config_mode: false
  content_match: NOVRF
  content_match_regex: false
  conversion_method: none
  creator: admin
  credentials: device
  custom_username: ''
  delay_factor: 1.0
  delete_spaces_before_matching: false
  description: ''
  device_query: ''
  device_query_property: name
  dict_match: {}
  display_only_failed_nodes: false
  driver: a10
  enable_mode: true
  expect_string: ''
  fast_cli: false
  global_delay_factor: 1.0
  hidden: false
  include_link_in_summary: false
  initial_payload: {}
  iteration_devices: ''
  iteration_devices_property: name
  iteration_values: ''
  iteration_variable_name: iteration_value
  last_modified: '2019-10-02 10:17:57.272976'
  mail_recipient: ''
  max_processes: 50
  maximum_runs: 1
  multiprocessing: false
  name: Check VRF (NOVRF) exists
  negative_logic: false
  notification_header: ''
  number_of_retries: 2
  operating_system: ''
  positions:
    'Regression Workflow 1: Netmiko with validation and retries': [250, -172]
  push_to_git: false
  result_postprocessing: ''
  send_notification: false
  send_notification_method: mail_feedback_notification
  skip: false
  skip_query: ''
  start_new_connection: false
  strip_command: true
  strip_prompt: true
  time_between_retries: 2
  timeout: 10
  type: netmiko_validation_service
  use_device_driver: true
  validation_method: text
  vendor: ''
  waiting_time: 0
