- color: pink
  creator: admin
  credentials: device
  custom_username: ''
  description: Start point of a workflow
  devices: []
  display_only_failed_nodes: true
  events: []
  has_targets: false
  hidden: true
  include_link_in_summary: true
  initial_payload: {}
  iteration_values: ''
  iteration_variable_name: iteration_value
  last_modified: '2019-06-24 07:19:52.482457'
  mail_recipient: ''
  max_processes: 5
  multiprocessing: false
  name: Start
  notification_header: ''
  number_of_retries: 0
  operating_system: ''
  pools: []
  positions:
    Configuration Management Workflow: !!python/tuple [-300, 0]
  push_to_git: false
  python_query: ''
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: circle
  size: 40
  skip: false
  skip_python_query: ''
  start_new_connection: false
  success_query: ''
  time_between_retries: 10
  type: SwissArmyKnifeService
  vendor: ''
  waiting_time: 0
- color: pink
  creator: admin
  credentials: device
  custom_username: ''
  description: End point of a workflow
  devices: []
  display_only_failed_nodes: true
  events: []
  has_targets: false
  hidden: true
  include_link_in_summary: true
  initial_payload: {}
  iteration_values: ''
  iteration_variable_name: iteration_value
  last_modified: '2019-06-24 07:19:52.491375'
  mail_recipient: ''
  max_processes: 5
  multiprocessing: false
  name: End
  notification_header: ''
  number_of_retries: 0
  operating_system: ''
  pools: []
  positions:
    Configuration Management Workflow: !!python/tuple [200, 0]
  push_to_git: false
  python_query: ''
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: circle
  size: 40
  skip: false
  skip_python_query: ''
  start_new_connection: false
  success_query: ''
  time_between_retries: 10
  type: SwissArmyKnifeService
  vendor: ''
  waiting_time: 0
- color: '#D2E5FF'
  creator: admin
  credentials: device
  custom_username: ''
  description: Mail notification (service logs)
  devices: []
  display_only_failed_nodes: true
  events: []
  has_targets: false
  hidden: false
  include_link_in_summary: true
  initial_payload: {}
  iteration_values: ''
  iteration_variable_name: iteration_value
  last_modified: '2019-06-24 07:19:52.498504'
  mail_recipient: ''
  max_processes: 5
  multiprocessing: false
  name: mail_feedback_notification
  notification_header: ''
  number_of_retries: 0
  operating_system: ''
  pools: []
  positions: {}
  push_to_git: false
  python_query: ''
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  skip: false
  skip_python_query: ''
  start_new_connection: false
  success_query: ''
  time_between_retries: 10
  type: SwissArmyKnifeService
  vendor: ''
  waiting_time: 0
- color: '#D2E5FF'
  creator: admin
  credentials: device
  custom_username: ''
  description: Slack notification (service logs)
  devices: []
  display_only_failed_nodes: true
  events: []
  has_targets: false
  hidden: false
  include_link_in_summary: true
  initial_payload: {}
  iteration_values: ''
  iteration_variable_name: iteration_value
  last_modified: '2019-06-24 07:19:52.506127'
  mail_recipient: ''
  max_processes: 5
  multiprocessing: false
  name: slack_feedback_notification
  notification_header: ''
  number_of_retries: 0
  operating_system: ''
  pools: []
  positions: {}
  push_to_git: false
  python_query: ''
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  skip: false
  skip_python_query: ''
  start_new_connection: false
  success_query: ''
  time_between_retries: 10
  type: SwissArmyKnifeService
  vendor: ''
  waiting_time: 0
- color: '#D2E5FF'
  creator: admin
  credentials: device
  custom_username: ''
  description: Mattermost notification (service logs)
  devices: []
  display_only_failed_nodes: true
  events: []
  has_targets: false
  hidden: false
  include_link_in_summary: true
  initial_payload: {}
  iteration_values: ''
  iteration_variable_name: iteration_value
  last_modified: '2019-06-24 07:19:52.514554'
  mail_recipient: ''
  max_processes: 5
  multiprocessing: false
  name: mattermost_feedback_notification
  notification_header: ''
  number_of_retries: 0
  operating_system: ''
  pools: []
  positions: {}
  push_to_git: false
  python_query: ''
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  skip: false
  skip_python_query: ''
  start_new_connection: false
  success_query: ''
  time_between_retries: 10
  type: SwissArmyKnifeService
  vendor: ''
  waiting_time: 0
- color: '#D2E5FF'
  creator: admin
  credentials: device
  custom_username: ''
  description: Monitor eNMS cluster
  devices: []
  display_only_failed_nodes: true
  events: []
  has_targets: false
  hidden: false
  include_link_in_summary: true
  initial_payload: {}
  iteration_values: ''
  iteration_variable_name: iteration_value
  last_modified: '2019-06-24 07:19:52.522003'
  mail_recipient: ''
  max_processes: 5
  multiprocessing: false
  name: cluster_monitoring
  notification_header: ''
  number_of_retries: 0
  operating_system: ''
  pools: []
  positions: {}
  push_to_git: false
  python_query: ''
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  skip: false
  skip_python_query: ''
  start_new_connection: false
  success_query: ''
  time_between_retries: 10
  type: SwissArmyKnifeService
  vendor: ''
  waiting_time: 0
- color: '#D2E5FF'
  creator: admin
  credentials: device
  custom_username: ''
  description: Push configurations to Gitlab
  devices: []
  display_only_failed_nodes: true
  events: []
  has_targets: false
  hidden: false
  include_link_in_summary: true
  initial_payload: {}
  iteration_values: ''
  iteration_variable_name: iteration_value
  last_modified: '2019-06-24 07:19:52.529269'
  mail_recipient: ''
  max_processes: 5
  multiprocessing: false
  name: git_push_configurations
  notification_header: ''
  number_of_retries: 0
  operating_system: ''
  pools: []
  positions:
    Configuration Management Workflow: !!python/tuple [0, 300]
  push_to_git: false
  python_query: ''
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  skip: false
  skip_python_query: ''
  start_new_connection: false
  success_query: ''
  time_between_retries: 10
  type: SwissArmyKnifeService
  vendor: ''
  waiting_time: 0
- color: '#D2E5FF'
  creator: admin
  credentials: device
  custom_username: ''
  description: Configuration Management Poller
  devices: []
  display_only_failed_nodes: true
  events: []
  has_targets: false
  hidden: true
  include_link_in_summary: true
  initial_payload: {}
  iteration_values: ''
  iteration_variable_name: iteration_value
  last_modified: '2019-06-24 07:19:52.536926'
  mail_recipient: ''
  max_processes: 5
  multiprocessing: false
  name: poller_service
  notification_header: ''
  number_of_retries: 0
  operating_system: ''
  pools: []
  positions:
    Configuration Management Workflow: !!python/tuple [0, -200]
  push_to_git: false
  python_query: ''
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  skip: false
  skip_python_query: ''
  start_new_connection: false
  success_query: ''
  time_between_retries: 10
  type: SwissArmyKnifeService
  vendor: ''
  waiting_time: 0
