- color: '#D2E5FF'
  completed: 0
  creator: admin
  credentials: device
  custom_username: ''
  define_devices_from_payload: false
  description: Poll configuration and push to gitlab
  devices: []
  display_only_failed_nodes: true
  events: []
  failed: 0
  has_targets: true
  hidden: false
  include_link_in_summary: true
  initial_payload: {}
  jobs:
  - Start
  - End
  - poller_service
  - git_push_configurations
  last_modified: '2019-07-17 15:32:25.068014'
  mail_recipient: ''
  name: Configuration Management Workflow
  notification_header: ''
  number_of_retries: 0
  number_of_targets: 0
  operating_system: ''
  pools: []
  positions: {}
  push_to_git: false
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: false
  vendor: ''
  waiting_time: 0
  yaql_query: ''
- color: '#D2E5FF'
  completed: 0
  creator: admin
  credentials: device
  custom_username: ''
  define_devices_from_payload: false
  description: Create and delete a VRF with Netmiko
  devices: []
  display_only_failed_nodes: true
  events: []
  failed: 0
  has_targets: true
  hidden: false
  include_link_in_summary: true
  initial_payload: {}
  jobs:
  - Start
  - End
  - netmiko_create_vrf_test
  - netmiko_check_vrf_test
  - netmiko_delete_vrf_test
  - netmiko_check_no_vrf_test
  last_modified: '2019-07-17 15:32:25.145148'
  mail_recipient: ''
  name: Netmiko_VRF_workflow
  notification_header: ''
  number_of_retries: 0
  number_of_targets: 1
  operating_system: eos
  pools:
  - Washington
  positions: {}
  push_to_git: false
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: true
  vendor: Arista
  waiting_time: 0
  yaql_query: ''
- color: '#D2E5FF'
  completed: 0
  creator: admin
  credentials: device
  custom_username: ''
  define_devices_from_payload: false
  description: Create and delete a VRF with Napalm
  devices:
  - Washington
  display_only_failed_nodes: true
  events: []
  failed: 0
  has_targets: true
  hidden: false
  include_link_in_summary: true
  initial_payload: {}
  jobs:
  - Start
  - End
  - napalm_create_vrf_test
  - napalm_rollback
  - netmiko_check_vrf_napalm
  - netmiko_check_no_vrf_napalm
  last_modified: '2019-07-17 15:32:25.255367'
  mail_recipient: ''
  name: Napalm_VRF_workflow
  notification_header: ''
  number_of_retries: 0
  number_of_targets: 1
  operating_system: eos
  pools: []
  positions:
    Workflow_of_workflows:
    - '0'
    - '200'
  push_to_git: false
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: true
  vendor: Arista
  waiting_time: 0
  yaql_query: ''
- color: '#D2E5FF'
  completed: 0
  creator: admin
  credentials: device
  custom_username: ''
  define_devices_from_payload: false
  description: ReST call, Napalm getters, etc
  devices:
  - Washington
  display_only_failed_nodes: true
  events: []
  failed: 0
  has_targets: true
  hidden: false
  include_link_in_summary: true
  initial_payload: {}
  jobs:
  - Start
  - End
  - get_facts
  - get_interfaces
  - get_interfaces_ip
  - get_config
  - process_payload1
  last_modified: '2019-07-17 15:32:25.352449'
  mail_recipient: ''
  name: payload_transfer_workflow
  notification_header: ''
  number_of_retries: 0
  number_of_targets: 1
  operating_system: eos
  pools: []
  positions:
    Workflow_of_workflows:
    - '0'
    - '-200'
  push_to_git: false
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: true
  vendor: Arista
  waiting_time: 0
  yaql_query: ''
- color: '#D2E5FF'
  completed: 0
  creator: admin
  credentials: device
  custom_username: ''
  define_devices_from_payload: false
  description: Test YaQL device selection mechanism
  devices:
  - Washington
  display_only_failed_nodes: true
  events: []
  failed: 0
  has_targets: true
  hidden: false
  include_link_in_summary: true
  initial_payload:
    derived_targets:
      Washington:
      - Washington
      - Baltimore
      - Fake device
  jobs:
  - Start
  - End
  - add_devices_to_payload
  - Iteration_service_simple
  - Iteration_service_yaql
  - Iteration_YaQL_derived_targets
  last_modified: '2019-07-17 15:32:25.429498'
  mail_recipient: ''
  name: YaQL_test_worflow
  notification_header: ''
  number_of_retries: 0
  number_of_targets: 1
  operating_system: ''
  pools: []
  positions: {}
  push_to_git: false
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: true
  vendor: ''
  waiting_time: 0
  yaql_query: ''
- color: '#D2E5FF'
  completed: 0
  creator: admin
  credentials: device
  custom_username: ''
  define_devices_from_payload: false
  description: Test the payload extraction and validation mechanisms
  devices:
  - Washington
  display_only_failed_nodes: true
  events: []
  failed: 0
  has_targets: true
  hidden: false
  include_link_in_summary: true
  initial_payload: {}
  jobs:
  - Start
  - End
  - netmiko_show_ip_route
  - payload_extraction
  - payload_validate_dict
  - payload_validate_text
  last_modified: '2019-07-17 15:32:25.507167'
  mail_recipient: ''
  name: payload_extraction_validation_worflow
  notification_header: ''
  number_of_retries: 0
  number_of_targets: 1
  operating_system: ''
  pools: []
  positions: {}
  push_to_git: false
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: true
  vendor: ''
  waiting_time: 0
  yaql_query: ''
- color: '#D2E5FF'
  completed: 0
  creator: admin
  credentials: device
  custom_username: ''
  define_devices_from_payload: false
  description: Test the inner workflow system
  devices:
  - Washington
  display_only_failed_nodes: true
  events: []
  failed: 0
  has_targets: true
  hidden: false
  include_link_in_summary: true
  initial_payload: {}
  jobs:
  - Start
  - End
  - payload_transfer_workflow
  - get_interfaces
  - Napalm_VRF_workflow
  last_modified: '2019-07-17 15:32:25.576776'
  mail_recipient: ''
  name: Workflow_of_workflows
  notification_header: ''
  number_of_retries: 0
  number_of_targets: 1
  operating_system: eos
  pools: []
  positions: {}
  push_to_git: false
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: true
  vendor: Arista
  waiting_time: 0
  yaql_query: ''
- color: '#D2E5FF'
  completed: 0
  creator: admin
  credentials: device
  custom_username: ''
  define_devices_from_payload: false
  description: Workflow with separate failure / success path
  devices:
  - Austin
  - Washington
  display_only_failed_nodes: false
  events: []
  failed: 0
  has_targets: true
  hidden: false
  include_link_in_summary: false
  initial_payload: {}
  jobs:
  - Start
  - End
  - get_facts
  - REST is_alive
  - netmiko_check_no_vrf_test
  last_modified: '2019-07-17 15:32:25.644163'
  mail_recipient: ''
  name: Workflow with separate failure / success path
  notification_header: ''
  number_of_retries: 0
  number_of_targets: 2
  operating_system: ''
  pools: []
  positions: {}
  push_to_git: false
  query_property_type: name
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: true
  vendor: ''
  waiting_time: 0
  yaql_query: ''
- color: '#D2E5FF'
  completed: 0
  creator: admin
  credentials: device
  custom_username: ''
  define_devices_from_payload: false
  description: ''
  devices:
  - Washington
  - Chicago
  display_only_failed_nodes: false
  events: []
  failed: 0
  has_targets: true
  hidden: false
  include_link_in_summary: false
  initial_payload:
    Chicago:
    - Baltimore
    - San Francisco
    Washington:
    - Austin
    - Dallas
  jobs:
  - Start
  - End
  - Device_from_yaql_query
  last_modified: '2019-07-17 15:36:34.790503'
  mail_recipient: ''
  name: yaql_query_workflow
  notification_header: ''
  number_of_retries: 0
  number_of_targets: 0
  operating_system: ''
  pools: []
  positions: {}
  push_to_git: false
  query_property_type: name
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: true
  vendor: ''
  waiting_time: 0
  yaql_query: ''
