- color: '#D2E5FF'
  completed: 0
  creator: admin
  credentials: device
  define_devices_from_payload: false
  description: Poll configuration and push to gitlab
  devices: []
  display_only_failed_nodes: true
  events: []
  failed: 0
  hidden: false
  jobs:
  - Start
  - End
  - poller_service
  - git_push_configurations
  last_modified: '2019-06-26 15:15:41.070057'
  mail_recipient: ''
  name: Configuration Management Workflow
  notification_header: ''
  number_of_retries: 0
  number_of_targets: 0
  operating_system: ''
  pools: []
  positions: {}
  push_to_git: false
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: false
  vendor: ''
  waiting_time: 0
  yaql_query: ''
- color: '#D2E5FF'
  completed: 0
  creator: admin
  credentials: device
  define_devices_from_payload: false
  description: Create and delete a VRF with Netmiko
  devices:
  - Washington
  - Austin
  display_only_failed_nodes: true
  events: []
  failed: 0
  hidden: false
  jobs:
  - Start
  - End
  - netmiko_create_vrf_test
  - netmiko_check_vrf_test
  - netmiko_delete_vrf_test
  - netmiko_check_no_vrf_test
  last_modified: '2019-06-26 15:15:41.165602'
  mail_recipient: ''
  name: Netmiko_VRF_workflow
  notification_header: ''
  number_of_retries: 0
  number_of_targets: 2
  operating_system: eos
  pools: []
  positions: {}
  push_to_git: false
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: true
  vendor: Arista
  waiting_time: 0
  yaql_query: ''
- color: '#D2E5FF'
  completed: 0
  creator: admin
  credentials: device
  define_devices_from_payload: false
  description: Create and delete a VRF with Napalm
  devices:
  - Washington
  display_only_failed_nodes: true
  events: []
  failed: 0
  hidden: false
  jobs:
  - Start
  - End
  - napalm_create_vrf_test
  - netmiko_check_vrf_test
  - netmiko_check_no_vrf_test
  - napalm_rollback
  last_modified: '2019-06-26 15:30:47.180480'
  mail_recipient: ''
  name: Napalm_VRF_workflow
  notification_header: ''
  number_of_retries: 0
  number_of_targets: 1
  operating_system: eos
  pools: []
  positions:
    Workflow_of_workflows:
    - '0'
    - '200'
  push_to_git: false
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: true
  vendor: Arista
  waiting_time: 0
  yaql_query: ''
- color: '#D2E5FF'
  completed: 0
  creator: admin
  credentials: device
  define_devices_from_payload: false
  description: ReST call, Napalm getters, etc
  devices:
  - Washington
  display_only_failed_nodes: true
  events: []
  failed: 0
  hidden: false
  jobs:
  - Start
  - End
  - GET_device
  - get_facts
  - get_interfaces
  - get_interfaces_ip
  - get_config
  - process_payload1
  last_modified: '2019-06-26 15:28:21.041664'
  mail_recipient: ''
  name: payload_transfer_workflow
  notification_header: ''
  number_of_retries: 0
  number_of_targets: 1
  operating_system: eos
  pools: []
  positions:
    Workflow_of_workflows:
    - '0'
    - '-200'
  push_to_git: false
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: true
  vendor: Arista
  waiting_time: 0
  yaql_query: ''
- color: '#D2E5FF'
  completed: 0
  creator: admin
  credentials: device
  define_devices_from_payload: false
  description: Test YaQL device selection mechanism
  devices:
  - Washington
  display_only_failed_nodes: true
  events: []
  failed: 0
  hidden: false
  jobs:
  - Start
  - End
  - add_devices_to_payload
  - netmiko_yaql_defined_devices
  - Iteration_service_simple
  - Iteration_service_yaql
  - netmiko_check_vrf_test
  - iteration_yaql_payload
  last_modified: '2019-06-26 15:15:41.467936'
  mail_recipient: ''
  name: YaQL_test_worflow
  notification_header: ''
  number_of_retries: 0
  number_of_targets: 1
  operating_system: ''
  pools: []
  positions: {}
  push_to_git: false
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: true
  vendor: ''
  waiting_time: 0
  yaql_query: ''
- color: '#D2E5FF'
  completed: 0
  creator: admin
  credentials: device
  define_devices_from_payload: false
  description: Test the payload extraction and validation mechanisms
  devices:
  - Washington
  display_only_failed_nodes: true
  events: []
  failed: 0
  hidden: false
  jobs:
  - Start
  - End
  - netmiko_show_ip_route
  - payload_extraction
  - payload_validate_dict
  - payload_validate_text
  last_modified: '2019-06-26 15:32:20.574586'
  mail_recipient: ''
  name: payload_extraction_validation_worflow
  notification_header: ''
  number_of_retries: 0
  number_of_targets: 1
  operating_system: ''
  pools: []
  positions: {}
  push_to_git: false
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: true
  vendor: ''
  waiting_time: 0
  yaql_query: ''
- color: '#D2E5FF'
  completed: 0
  creator: admin
  credentials: device
  define_devices_from_payload: false
  description: Test the inner workflow system
  devices:
  - Washington
  display_only_failed_nodes: true
  events: []
  failed: 0
  hidden: false
  jobs:
  - Start
  - End
  - payload_transfer_workflow
  - get_interfaces
  - Napalm_VRF_workflow
  last_modified: '2019-06-26 15:15:41.635678'
  mail_recipient: ''
  name: Workflow_of_workflows
  notification_header: ''
  number_of_retries: 0
  number_of_targets: 1
  operating_system: eos
  pools: []
  positions: {}
  push_to_git: false
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: true
  vendor: Arista
  waiting_time: 0
  yaql_query: ''
