- completed: 0
  creator: admin
  credentials: device
  notification_header: ''
  define_devices_from_payload: false
  description: Poll configuration and push to gitlab
  devices: []
  display_only_failed_nodes: true
  events: []
  failed: 0
  hidden: false
  jobs:
  - Start
  - End
  - poller_service
  - git_push_configurations
  last_modified: '2019-06-24 10:14:18.797715'
  mail_recipient: ''
  name: Configuration Management Workflow
  number_of_retries: 0
  number_of_targets: 0
  operating_system: ''
  pools: []
  positions: {}
  push_to_git: false
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: false
  vendor: ''
  waiting_time: 0
  yaql_query: ''
- completed: 0
  creator: admin
  credentials: device
  notification_header: ''
  define_devices_from_payload: false
  description: Create and delete a VRF with Netmiko
  devices:
  - Washington
  - Austin
  display_only_failed_nodes: true
  events: []
  failed: 0
  hidden: false
  jobs:
  - Start
  - End
  - netmiko_create_vrf_test
  - netmiko_check_vrf_test
  - netmiko_delete_vrf_test
  - netmiko_check_no_vrf_test
  last_modified: '2019-06-24 10:14:18.876557'
  mail_recipient: ''
  name: Netmiko_VRF_workflow
  number_of_retries: 0
  number_of_targets: 2
  operating_system: eos
  pools: []
  positions: {}
  push_to_git: false
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: true
  vendor: Arista
  waiting_time: 0
  yaql_query: ''
- completed: 0
  creator: admin
  credentials: device
  notification_header: ''
  define_devices_from_payload: false
  description: Create and delete a VRF with Napalm
  devices:
  - Washington
  - Austin
  display_only_failed_nodes: true
  events: []
  failed: 0
  hidden: false
  jobs:
  - Start
  - End
  - napalm_create_vrf_test
  - netmiko_check_vrf_test
  - netmiko_check_no_vrf_test
  - napalm_rollback
  last_modified: '2019-06-24 10:19:37.762568'
  mail_recipient: ''
  name: Napalm_VRF_workflow
  number_of_retries: 0
  number_of_targets: 2
  operating_system: eos
  pools: []
  positions:
    Workflow_of_workflows:
    - '0'
    - '200'
  push_to_git: false
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: true
  vendor: Arista
  waiting_time: 0
  yaql_query: ''
- completed: 0
  creator: admin
  credentials: device
  notification_header: ''
  define_devices_from_payload: false
  description: ReST call, Napalm getters, etc
  devices:
  - Washington
  - Austin
  display_only_failed_nodes: true
  events: []
  failed: 0
  hidden: false
  jobs:
  - Start
  - End
  - GET_device
  - get_facts
  - get_interfaces
  - get_interfaces_ip
  - get_config
  - process_payload1
  last_modified: '2019-06-24 10:14:19.015710'
  mail_recipient: ''
  name: payload_transfer_workflow
  number_of_retries: 0
  number_of_targets: 0
  operating_system: eos
  pools: []
  positions:
    Workflow_of_workflows:
    - '0'
    - '-200'
  push_to_git: false
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: true
  vendor: Arista
  waiting_time: 0
  yaql_query: ''
- completed: 0
  creator: admin
  credentials: device
  notification_header: ''
  define_devices_from_payload: false
  description: Test YaQL device selection mechanism
  devices: []
  display_only_failed_nodes: true
  events: []
  failed: 0
  hidden: false
  jobs:
  - Start
  - End
  - add_devices_to_payload
  - netmiko_yaql_defined_devices
  - Iteration_service_simple
  - Iteration_service_yaql
  last_modified: '2019-06-24 10:14:19.068461'
  mail_recipient: ''
  name: YaQL_test_worflow
  number_of_retries: 0
  number_of_targets: 0
  operating_system: ''
  pools: []
  positions: {}
  push_to_git: false
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: false
  vendor: ''
  waiting_time: 0
  yaql_query: ''
- completed: 0
  creator: admin
  credentials: device
  notification_header: ''
  define_devices_from_payload: false
  description: Test the payload extraction and validation mechanisms
  devices:
  - Washington
  - Austin
  display_only_failed_nodes: true
  events: []
  failed: 0
  hidden: false
  jobs:
  - Start
  - End
  - netmiko_show_ip_route
  - payload_extraction
  - payload_validate_dict
  - payload_validate_text
  last_modified: '2019-06-24 10:14:19.136625'
  mail_recipient: ''
  name: payload_extraction_validation_worflow
  number_of_retries: 0
  number_of_targets: 0
  operating_system: ''
  pools: []
  positions: {}
  push_to_git: false
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: true
  vendor: ''
  waiting_time: 0
  yaql_query: ''
- completed: 0
  creator: admin
  credentials: device
  notification_header: ''
  define_devices_from_payload: false
  description: Test the inner workflow system
  devices:
  - Washington
  display_only_failed_nodes: true
  events: []
  failed: 0
  hidden: false
  jobs:
  - Start
  - End
  - payload_transfer_workflow
  - get_interfaces
  - Napalm_VRF_workflow
  last_modified: '2019-06-24 10:14:19.201650'
  mail_recipient: ''
  name: Workflow_of_workflows
  number_of_retries: 0
  number_of_targets: 0
  operating_system: eos
  pools: []
  positions: {}
  push_to_git: false
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: true
  vendor: Arista
  waiting_time: 0
  yaql_query: ''
