- color: '#D2E5FF'
  creator: admin
  credentials: device
  custom_username: ''
  description: Poll configuration and push to gitlab
  devices: []
  display_only_failed_nodes: true
  events: []
  has_targets: true
  hidden: false
  include_link_in_summary: true
  initial_payload: {}
  jobs: [Start, End, poller_service, git_push_configurations]
  last_modified: '2019-08-05 13:30:56.726895'
  mail_recipient: ''
  name: Configuration Management Workflow
  notification_header: ''
  number_of_retries: 0
  operating_system: ''
  pools: []
  positions: {}
  push_to_git: false
  python_query: ''
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  skip: false
  skip_python_query: ''
  start_jobs: [Start]
  start_new_connection: false
  start_workflows: []
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: false
  vendor: ''
  waiting_time: 0
- color: '#D2E5FF'
  creator: admin
  credentials: device
  custom_username: ''
  description: Create and delete a VRF with Netmiko
  devices: [Austin]
  display_only_failed_nodes: true
  events: []
  has_targets: true
  hidden: false
  include_link_in_summary: true
  initial_payload: {}
  jobs: [Start, End, netmiko_create_vrf_test, netmiko_check_vrf_test, netmiko_delete_vrf_test,
    netmiko_check_no_vrf_test]
  last_modified: '2019-08-05 13:30:56.803035'
  mail_recipient: ''
  name: Netmiko_VRF_workflow
  notification_header: ''
  number_of_retries: 0
  operating_system: eos
  pools: [Washington]
  positions: {}
  push_to_git: false
  python_query: ''
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  skip: false
  skip_python_query: ''
  start_jobs: [Start]
  start_new_connection: false
  start_workflows: []
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: true
  vendor: Arista
  waiting_time: 0
- color: '#D2E5FF'
  creator: admin
  credentials: device
  custom_username: ''
  description: Create and delete a VRF with Napalm
  devices: [Washington]
  display_only_failed_nodes: true
  events: []
  has_targets: true
  hidden: false
  include_link_in_summary: true
  initial_payload: {}
  jobs: [Start, End, napalm_create_vrf_test, napalm_rollback, netmiko_check_vrf_napalm,
    netmiko_check_no_vrf_napalm]
  last_modified: '2019-08-05 13:30:56.889198'
  mail_recipient: ''
  name: Napalm_VRF_workflow
  notification_header: ''
  number_of_retries: 0
  operating_system: eos
  pools: []
  positions:
    Workflow_of_workflows: ['0', '200']
  push_to_git: false
  python_query: ''
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  skip: false
  skip_python_query: ''
  start_jobs: [Start]
  start_new_connection: false
  start_workflows: []
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: true
  vendor: Arista
  waiting_time: 0
- color: '#D2E5FF'
  creator: admin
  credentials: device
  custom_username: ''
  description: ReST call, Napalm getters, etc
  devices: [Washington]
  display_only_failed_nodes: true
  events: []
  has_targets: true
  hidden: false
  include_link_in_summary: true
  initial_payload: {}
  jobs: [Start, End, get_facts, get_interfaces, get_interfaces_ip, get_config, process_payload1]
  last_modified: '2019-08-05 13:30:56.982753'
  mail_recipient: ''
  name: payload_transfer_workflow
  notification_header: ''
  number_of_retries: 0
  operating_system: eos
  pools: []
  positions:
    Workflow_of_workflows: ['0', '-200']
  push_to_git: false
  python_query: ''
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  skip: false
  skip_python_query: ''
  start_jobs: [Start]
  start_new_connection: false
  start_workflows: []
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: true
  vendor: Arista
  waiting_time: 0
- color: '#D2E5FF'
  creator: admin
  credentials: device
  custom_username: ''
  description: Test python device selection mechanism
  devices: [Washington, Austin]
  display_only_failed_nodes: true
  events: []
  has_targets: true
  hidden: false
  include_link_in_summary: true
  initial_payload: {}
  jobs: [Start, End, add_devices_to_payload, Iteration_service_simple, Iteration_service_python]
  last_modified: '2019-08-05 13:30:57.049335'
  mail_recipient: ''
  name: Iteration Services Test Workflow
  notification_header: ''
  number_of_retries: 0
  operating_system: ''
  pools: []
  positions: {}
  push_to_git: false
  python_query: ''
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  skip: false
  skip_python_query: ''
  start_jobs: [Start]
  start_new_connection: false
  start_workflows: []
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: true
  vendor: ''
  waiting_time: 0
- color: '#D2E5FF'
  creator: admin
  credentials: device
  custom_username: ''
  description: Test the payload extraction and validation mechanisms
  devices: [Washington]
  display_only_failed_nodes: true
  events: []
  has_targets: true
  hidden: false
  include_link_in_summary: true
  initial_payload: {}
  jobs: [Start, End, netmiko_show_ip_route, payload_extraction, payload_validate_dict,
    payload_validate_text]
  last_modified: '2019-08-05 13:30:57.124601'
  mail_recipient: ''
  name: payload_extraction_validation_worflow
  notification_header: ''
  number_of_retries: 0
  operating_system: ''
  pools: []
  positions: {}
  push_to_git: false
  python_query: ''
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  skip: false
  skip_python_query: ''
  start_jobs: [Start]
  start_new_connection: false
  start_workflows: []
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: true
  vendor: ''
  waiting_time: 0
- color: '#D2E5FF'
  creator: admin
  credentials: device
  custom_username: ''
  description: Test the inner workflow system
  devices: [Washington]
  display_only_failed_nodes: true
  events: []
  has_targets: true
  hidden: false
  include_link_in_summary: true
  initial_payload: {}
  jobs: [Start, End, payload_transfer_workflow, get_interfaces, Napalm_VRF_workflow]
  last_modified: '2019-08-05 13:30:57.198567'
  mail_recipient: antoine.fourmy@gmail.com
  name: Workflow_of_workflows
  notification_header: ''
  number_of_retries: 0
  operating_system: eos
  pools: []
  positions: {}
  push_to_git: false
  python_query: ''
  query_property_type: ip_address
  send_notification: true
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  skip: false
  skip_python_query: ''
  start_jobs: [Start]
  start_new_connection: false
  start_workflows: []
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: true
  vendor: Arista
  waiting_time: 0
- color: '#D2E5FF'
  creator: admin
  credentials: device
  custom_username: ''
  description: Workflow with separate failure - success path
  devices: [Austin, Washington]
  display_only_failed_nodes: false
  events: []
  has_targets: true
  hidden: false
  include_link_in_summary: false
  initial_payload: {}
  jobs: [Start, End, get_facts, REST is_alive, netmiko_check_no_vrf_test]
  last_modified: '2019-08-05 13:30:57.271404'
  mail_recipient: ''
  name: Workflow with separate failure - success path
  notification_header: ''
  number_of_retries: 0
  operating_system: ''
  pools: []
  positions: {}
  push_to_git: false
  python_query: ''
  query_property_type: name
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  skip: false
  skip_python_query: ''
  start_jobs: [Start]
  start_new_connection: false
  start_workflows: []
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: true
  vendor: ''
  waiting_time: 0
- color: '#D2E5FF'
  creator: admin
  credentials: device
  custom_username: ''
  description: ''
  devices: [Washington]
  display_only_failed_nodes: false
  events: []
  has_targets: true
  hidden: false
  include_link_in_summary: false
  initial_payload: {}
  jobs: [Start, End, Test Netmiko Prompt Service, Test netmiko prompts pass]
  last_modified: '2019-08-05 13:30:57.333759'
  mail_recipient: ''
  name: Netmiko prompts
  notification_header: ''
  number_of_retries: 0
  operating_system: ''
  pools: []
  positions: {}
  push_to_git: false
  python_query: ''
  query_property_type: name
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  skip: false
  skip_python_query: ''
  start_jobs: [Start]
  start_new_connection: false
  start_workflows: []
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: true
  vendor: ''
  waiting_time: 0
- color: '#D2E5FF'
  creator: admin
  credentials: device
  custom_username: ''
  description: ''
  devices: [Washington, Chicago]
  display_only_failed_nodes: false
  events: []
  has_targets: true
  hidden: false
  include_link_in_summary: false
  initial_payload: {}
  jobs: [Start, End, 'Payload editor, no devices', 'Payload editor, with device',
    Show vrf with payload helper, Show vrf with python query, REST is_alive, show
      runtime with get_result helper]
  last_modified: '2019-08-05 13:30:57.426946'
  mail_recipient: ''
  name: 'python Workflow: payload editor and pool helper'
  notification_header: ''
  number_of_retries: 0
  operating_system: ''
  pools: []
  positions: {}
  push_to_git: false
  python_query: ''
  query_property_type: name
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  skip: false
  skip_python_query: ''
  start_jobs: [Start]
  start_new_connection: false
  start_workflows: []
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: true
  vendor: ''
  waiting_time: 0
- color: '#D2E5FF'
  creator: admin
  credentials: device
  custom_username: ''
  description: ''
  devices: [Washington]
  display_only_failed_nodes: false
  events: []
  has_targets: true
  hidden: false
  include_link_in_summary: false
  initial_payload: {}
  jobs: [Start, End, 'Getters Workflow: is alive', 'Getters Workflow: get facts',
    'Getters Workflow: Interface IP', 'Getters Workflow: MAC address', 'Getters Workflow:
      get facts failed match']
  last_modified: '2019-08-06 22:24:59.221849'
  mail_recipient: ''
  name: Napalm getters and match mechanism workflow
  notification_header: ''
  number_of_retries: 0
  operating_system: ''
  pools: []
  positions: {}
  push_to_git: false
  python_query: ''
  query_property_type: name
  send_notification: false
  send_notification_method: mail_feedback_notification
  shape: box
  size: 40
  skip: false
  skip_python_query: ''
  start_jobs: [Start]
  start_new_connection: false
  start_workflows: []
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: true
  vendor: ''
  waiting_time: 0
