color: '#D2E5FF'
completed: 0
creator: admin
credentials: device
define_devices_from_payload: false
description: Create and delete a VRF with Napalm
devices:
- Washington
display_only_failed_nodes: true
events: []
failed: 0
has_targets: true
hidden: false
jobs:
- Start
- End
- napalm_create_vrf_test
- napalm_rollback
- netmiko_check_vrf_napalm
- netmiko_check_no_vrf_napalm
last_modified: '2019-06-29 17:13:33.451325'
mail_recipient: ''
name: Napalm_VRF_workflow
notification_header: ''
number_of_retries: 0
number_of_targets: 1
operating_system: eos
payload: {}
pools: []
positions:
  Workflow_of_workflows:
  - '0'
  - '200'
push_to_git: false
query_property_type: ip_address
send_notification: false
send_notification_method: mail_feedback_notification
shape: box
size: 40
time_between_retries: 10
type: Workflow
use_workflow_targets: true
vendor: Arista
waiting_time: 0
yaql_query: ''
