- description: Start point of a workflow
  devices: []
  id: 1
  name: Start
  number_of_retries: 0
  operating_system: null
  pools: []
  positions: !!python/object/new:sqlalchemy.ext.mutable.MutableDict
    dictitems:
      Napalm_VRF_workflow: &id001 !!python/tuple
      - -200
      - 0
      Netmiko_VRF_workflow: &id002 !!python/tuple
      - -200
      - 0
      payload_transfer_workflow: &id003 !!python/tuple
      - -200
      - 0
    state:
      Napalm_VRF_workflow: *id001
      Netmiko_VRF_workflow: *id002
      payload_transfer_workflow: *id003
  send_notification: false
  send_notification_method: mail_feedback_notification
  status: Idle
  time_between_retries: 10
  type: SwissArmyKnifeService
  vendor: null
  waiting_time: 0
- description: End point of a workflow
  devices: []
  id: 2
  name: End
  number_of_retries: 0
  operating_system: null
  pools: []
  positions: !!python/object/new:sqlalchemy.ext.mutable.MutableDict
    dictitems:
      Napalm_VRF_workflow: &id004 !!python/tuple
      - 200
      - 0
      Netmiko_VRF_workflow: &id005 !!python/tuple
      - 200
      - 0
      payload_transfer_workflow: &id006 !!python/tuple
      - 500
      - 0
    state:
      Napalm_VRF_workflow: *id004
      Netmiko_VRF_workflow: *id005
      payload_transfer_workflow: *id006
  send_notification: false
  send_notification_method: mail_feedback_notification
  status: Idle
  time_between_retries: 10
  type: SwissArmyKnifeService
  vendor: null
  waiting_time: 0
- description: Mail notification (service logs)
  devices: []
  id: 3
  name: mail_feedback_notification
  number_of_retries: 0
  operating_system: null
  pools: []
  positions: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  send_notification: false
  send_notification_method: mail_feedback_notification
  status: Idle
  time_between_retries: 10
  type: SwissArmyKnifeService
  vendor: null
  waiting_time: 0
- description: Slack notification (service logs)
  devices: []
  id: 4
  name: slack_feedback_notification
  number_of_retries: 0
  operating_system: null
  pools: []
  positions: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  send_notification: false
  send_notification_method: mail_feedback_notification
  status: Idle
  time_between_retries: 10
  type: SwissArmyKnifeService
  vendor: null
  waiting_time: 0
- description: Mattermost notification (service logs)
  devices: []
  id: 5
  name: mattermost_feedback_notification
  number_of_retries: 0
  operating_system: null
  pools: []
  positions: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  send_notification: false
  send_notification_method: mail_feedback_notification
  status: Idle
  time_between_retries: 10
  type: SwissArmyKnifeService
  vendor: null
  waiting_time: 0
- description: Configure BGP Peering with Napalm
  devices:
  - 4
  id: 6
  local_as: 100
  loopback: Lo100
  loopback_ip: 100.1.1.1
  name: napalm_configure_bgp_1
  neighbor_ip: 100.1.2.1
  number_of_retries: 0
  operating_system: null
  pools: []
  positions: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  remote_as: 200
  send_notification: false
  send_notification_method: mail_feedback_notification
  status: Idle
  time_between_retries: 10
  type: ConfigureBgpService
  vendor: null
  vrf_name: configure_BGP_test
  waiting_time: 0
- content: vrf definition test
  description: Create a VRF "test" with Netmiko
  devices:
  - 4
  driver: arista_eos
  enable_mode: true
  fast_cli: true
  global_delay_factor: 1.0
  id: 7
  name: netmiko_create_vrf_test
  number_of_retries: 0
  operating_system: eos
  pools: []
  positions: !!python/object/new:sqlalchemy.ext.mutable.MutableDict
    dictitems:
      Netmiko_VRF_workflow: &id007 !!python/tuple
      - 0
      - -150
    state:
      Netmiko_VRF_workflow: *id007
  send_notification: false
  send_notification_method: mail_feedback_notification
  status: Idle
  time_between_retries: 10
  timeout: 3
  type: NetmikoConfigurationService
  vendor: Arista
  waiting_time: 0
- command: show vrf
  content_match: test
  content_match_regex: null
  description: Check that the vrf "test" is configured
  devices:
  - 4
  driver: arista_eos
  fast_cli: true
  global_delay_factor: 1.0
  id: 8
  name: netmiko_check_vrf_test
  number_of_retries: 0
  operating_system: eos
  pools: []
  positions: !!python/object/new:sqlalchemy.ext.mutable.MutableDict
    dictitems:
      Napalm_VRF_workflow: &id008 !!python/tuple
      - 0
      - -50
      Netmiko_VRF_workflow: &id009 !!python/tuple
      - 0
      - -50
    state:
      Napalm_VRF_workflow: *id008
      Netmiko_VRF_workflow: *id009
  send_notification: false
  send_notification_method: mail_feedback_notification
  status: Idle
  time_between_retries: 10
  timeout: 3
  type: NetmikoValidationService
  vendor: Arista
  waiting_time: 0
- content: no vrf definition test
  description: Delete VRF "test"
  devices:
  - 4
  driver: arista_eos
  enable_mode: true
  fast_cli: true
  global_delay_factor: 1.0
  id: 9
  name: netmiko_delete_vrf_test
  number_of_retries: 0
  operating_system: eos
  pools: []
  positions: !!python/object/new:sqlalchemy.ext.mutable.MutableDict
    dictitems:
      Netmiko_VRF_workflow: &id010 !!python/tuple
      - 0
      - 50
    state:
      Netmiko_VRF_workflow: *id010
  send_notification: false
  send_notification_method: mail_feedback_notification
  status: Idle
  time_between_retries: 10
  timeout: 3
  type: NetmikoConfigurationService
  vendor: Arista
  waiting_time: 1
- command: show vrf
  content_match: ^((?!test)[\s\S])*$
  content_match_regex: true
  description: Check that the vrf "test" is NOT configured
  devices:
  - 4
  driver: arista_eos
  fast_cli: true
  global_delay_factor: 1.0
  id: 10
  name: netmiko_check_no_vrf_test
  number_of_retries: 2
  operating_system: eos
  pools: []
  positions: !!python/object/new:sqlalchemy.ext.mutable.MutableDict
    dictitems:
      Napalm_VRF_workflow: &id011 !!python/tuple
      - 0
      - 150
      Netmiko_VRF_workflow: &id012 !!python/tuple
      - 0
      - 150
    state:
      Napalm_VRF_workflow: *id011
      Netmiko_VRF_workflow: *id012
  send_notification: false
  send_notification_method: mail_feedback_notification
  status: Idle
  time_between_retries: 1
  timeout: 3
  type: NetmikoValidationService
  vendor: Arista
  waiting_time: 0
- action: load_merge_candidate
  content: 'vrf definition test

    '
  description: Create a VRF "test" with Napalm
  devices:
  - 4
  driver: eos
  id: 12
  name: napalm_create_vrf_test
  number_of_retries: 0
  operating_system: eos
  optional_args: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  pools: []
  positions: !!python/object/new:sqlalchemy.ext.mutable.MutableDict
    dictitems:
      Napalm_VRF_workflow: &id013 !!python/tuple
      - 0
      - -150
    state:
      Napalm_VRF_workflow: *id013
  send_notification: false
  send_notification_method: mail_feedback_notification
  status: Idle
  time_between_retries: 10
  type: NapalmConfigurationService
  vendor: Arista
  waiting_time: 0
- description: Rollback a configuration with Napalm eos
  devices:
  - 4
  driver: eos
  id: 13
  name: Napalm eos Rollback
  number_of_retries: 0
  operating_system: null
  optional_args: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  pools: []
  positions: !!python/object/new:sqlalchemy.ext.mutable.MutableDict
    dictitems:
      Napalm_VRF_workflow: &id014 !!python/tuple
      - 0
      - 50
    state:
      Napalm_VRF_workflow: *id014
  send_notification: false
  send_notification_method: mail_feedback_notification
  status: Idle
  time_between_retries: 10
  type: NapalmRollbackService
  vendor: null
  waiting_time: 0
- call_type: GET
  content_match: ''
  content_match_regex: null
  description: Use GET ReST call on eNMS ReST API
  devices:
  - 4
  id: 15
  name: GET_device
  number_of_retries: 0
  operating_system: null
  payload: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  pools: []
  positions: !!python/object/new:sqlalchemy.ext.mutable.MutableDict
    dictitems:
      payload_transfer_workflow: &id015 !!python/tuple
      - -50
      - 0
    state:
      payload_transfer_workflow: *id015
  send_notification: false
  send_notification_method: mail_feedback_notification
  status: Idle
  time_between_retries: 10
  type: RestCallService
  url: http://127.0.0.1:5000/rest/object/device/{{device.name}}
  username: admin
  vendor: null
  waiting_time: 0
- content_match: ''
  content_match_regex: null
  description: 'Getter: get_facts'
  devices:
  - 4
  driver: eos
  getters: !!python/object/new:sqlalchemy.ext.mutable.MutableList
    listitems:
    - get_facts
    state:
    - get_facts
  id: 16
  name: get_facts
  number_of_retries: 0
  operating_system: null
  optional_args: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  pools: []
  positions: !!python/object/new:sqlalchemy.ext.mutable.MutableDict
    dictitems:
      payload_transfer_workflow: &id016 !!python/tuple
      - -50
      - -100
    state:
      payload_transfer_workflow: *id016
  send_notification: false
  send_notification_method: mail_feedback_notification
  status: Idle
  time_between_retries: 10
  type: NapalmGettersService
  vendor: null
  waiting_time: 0
- content_match: ''
  content_match_regex: null
  description: 'Getter: get_interfaces'
  devices:
  - 4
  driver: eos
  getters: !!python/object/new:sqlalchemy.ext.mutable.MutableList
    listitems:
    - get_interfaces
    state:
    - get_interfaces
  id: 17
  name: get_interfaces
  number_of_retries: 0
  operating_system: null
  optional_args: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  pools: []
  positions: !!python/object/new:sqlalchemy.ext.mutable.MutableDict
    dictitems:
      payload_transfer_workflow: &id017 !!python/tuple
      - 150
      - 100
    state:
      payload_transfer_workflow: *id017
  send_notification: false
  send_notification_method: mail_feedback_notification
  status: Idle
  time_between_retries: 10
  type: NapalmGettersService
  vendor: null
  waiting_time: 0
- content_match: ''
  content_match_regex: null
  description: 'Getter: get_interfaces_ip'
  devices:
  - 4
  driver: eos
  getters: !!python/object/new:sqlalchemy.ext.mutable.MutableList
    listitems:
    - get_interfaces_ip
    state:
    - get_interfaces_ip
  id: 18
  name: get_interfaces_ip
  number_of_retries: 0
  operating_system: null
  optional_args: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  pools: []
  positions: !!python/object/new:sqlalchemy.ext.mutable.MutableDict
    dictitems:
      payload_transfer_workflow: &id018 !!python/tuple
      - 150
      - -100
    state:
      payload_transfer_workflow: *id018
  send_notification: false
  send_notification_method: mail_feedback_notification
  status: Idle
  time_between_retries: 10
  type: NapalmGettersService
  vendor: null
  waiting_time: 0
- content_match: ''
  content_match_regex: null
  description: 'Getter: get_config'
  devices:
  - 4
  driver: eos
  getters: !!python/object/new:sqlalchemy.ext.mutable.MutableList
    listitems:
    - get_config
    state:
    - get_config
  id: 19
  name: get_config
  number_of_retries: 0
  operating_system: null
  optional_args: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  pools: []
  positions: !!python/object/new:sqlalchemy.ext.mutable.MutableDict
    dictitems:
      payload_transfer_workflow: &id019 !!python/tuple
      - 300
      - -100
    state:
      payload_transfer_workflow: *id019
  send_notification: false
  send_notification_method: mail_feedback_notification
  status: Idle
  time_between_retries: 10
  type: NapalmGettersService
  vendor: null
  waiting_time: 0
- description: Process Payload in example workflow
  devices:
  - 4
  id: 20
  name: process_payload1
  number_of_retries: 0
  operating_system: null
  pools: []
  positions: !!python/object/new:sqlalchemy.ext.mutable.MutableDict
    dictitems:
      payload_transfer_workflow: &id020 !!python/tuple
      - 300
      - 0
    state:
      payload_transfer_workflow: *id020
  send_notification: false
  send_notification_method: mail_feedback_notification
  status: Idle
  time_between_retries: 10
  type: SwissArmyKnifeService
  vendor: null
  waiting_time: 0
