- completed: 0
  creator: admin
  credentials: device
  custom_notification: false
  define_devices_from_payload: false
  description: Start point of a workflow
  devices: []
  display_only_failed_nodes: true
  events: []
  failed: 0
  has_targets: false
  hidden: true
  last_modified: '2019-06-24 06:59:41.952856'
  mail_recipient: ''
  max_processes: 5
  multiprocessing: false
  name: Start
  number_of_retries: 0
  number_of_targets: 0
  operating_system: ''
  pools: []
  positions:
    Configuration Management Workflow: !!python/tuple
    - -300
    - 0
  push_to_git: false
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  time_between_retries: 10
  type: SwissArmyKnifeService
  vendor: ''
  waiting_time: 0
  yaql_query: ''
- completed: 0
  creator: admin
  credentials: device
  custom_notification: false
  define_devices_from_payload: false
  description: End point of a workflow
  devices: []
  display_only_failed_nodes: true
  events: []
  failed: 0
  has_targets: false
  hidden: true
  last_modified: '2019-06-24 06:59:41.961712'
  mail_recipient: ''
  max_processes: 5
  multiprocessing: false
  name: End
  number_of_retries: 0
  number_of_targets: 0
  operating_system: ''
  pools: []
  positions:
    Configuration Management Workflow: !!python/tuple
    - 200
    - 0
  push_to_git: false
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  time_between_retries: 10
  type: SwissArmyKnifeService
  vendor: ''
  waiting_time: 0
  yaql_query: ''
- completed: 0
  creator: admin
  credentials: device
  custom_notification: false
  define_devices_from_payload: false
  description: Mail notification (service logs)
  devices: []
  display_only_failed_nodes: true
  events: []
  failed: 0
  has_targets: false
  hidden: false
  last_modified: '2019-06-24 06:59:41.969377'
  mail_recipient: ''
  max_processes: 5
  multiprocessing: false
  name: mail_feedback_notification
  number_of_retries: 0
  number_of_targets: 0
  operating_system: ''
  pools: []
  positions: {}
  push_to_git: false
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  time_between_retries: 10
  type: SwissArmyKnifeService
  vendor: ''
  waiting_time: 0
  yaql_query: ''
- completed: 0
  creator: admin
  credentials: device
  custom_notification: false
  define_devices_from_payload: false
  description: Slack notification (service logs)
  devices: []
  display_only_failed_nodes: true
  events: []
  failed: 0
  has_targets: false
  hidden: false
  last_modified: '2019-06-24 06:59:41.975680'
  mail_recipient: ''
  max_processes: 5
  multiprocessing: false
  name: slack_feedback_notification
  number_of_retries: 0
  number_of_targets: 0
  operating_system: ''
  pools: []
  positions: {}
  push_to_git: false
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  time_between_retries: 10
  type: SwissArmyKnifeService
  vendor: ''
  waiting_time: 0
  yaql_query: ''
- completed: 0
  creator: admin
  credentials: device
  custom_notification: false
  define_devices_from_payload: false
  description: Mattermost notification (service logs)
  devices: []
  display_only_failed_nodes: true
  events: []
  failed: 0
  has_targets: false
  hidden: false
  last_modified: '2019-06-24 06:59:41.984702'
  mail_recipient: ''
  max_processes: 5
  multiprocessing: false
  name: mattermost_feedback_notification
  number_of_retries: 0
  number_of_targets: 0
  operating_system: ''
  pools: []
  positions: {}
  push_to_git: false
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  time_between_retries: 10
  type: SwissArmyKnifeService
  vendor: ''
  waiting_time: 0
  yaql_query: ''
- completed: 0
  creator: admin
  credentials: device
  custom_notification: false
  define_devices_from_payload: false
  description: Monitor eNMS cluster
  devices: []
  display_only_failed_nodes: true
  events: []
  failed: 0
  has_targets: false
  hidden: false
  last_modified: '2019-06-24 06:59:41.992270'
  mail_recipient: ''
  max_processes: 5
  multiprocessing: false
  name: cluster_monitoring
  number_of_retries: 0
  number_of_targets: 0
  operating_system: ''
  pools: []
  positions: {}
  push_to_git: false
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  time_between_retries: 10
  type: SwissArmyKnifeService
  vendor: ''
  waiting_time: 0
  yaql_query: ''
- completed: 0
  creator: admin
  credentials: device
  custom_notification: false
  define_devices_from_payload: false
  description: Push configurations to Gitlab
  devices: []
  display_only_failed_nodes: true
  events: []
  failed: 0
  has_targets: false
  hidden: false
  last_modified: '2019-06-24 06:59:42.000799'
  mail_recipient: ''
  max_processes: 5
  multiprocessing: false
  name: git_push_configurations
  number_of_retries: 0
  number_of_targets: 0
  operating_system: ''
  pools: []
  positions:
    Configuration Management Workflow: !!python/tuple
    - 0
    - 300
  push_to_git: false
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  time_between_retries: 10
  type: SwissArmyKnifeService
  vendor: ''
  waiting_time: 0
  yaql_query: ''
- completed: 0
  creator: admin
  credentials: device
  custom_notification: false
  define_devices_from_payload: false
  description: Configuration Management Poller
  devices: []
  display_only_failed_nodes: true
  events: []
  failed: 0
  has_targets: false
  hidden: true
  last_modified: '2019-06-24 06:59:42.013939'
  mail_recipient: ''
  max_processes: 5
  multiprocessing: false
  name: poller_service
  number_of_retries: 0
  number_of_targets: 0
  operating_system: ''
  pools: []
  positions:
    Configuration Management Workflow: !!python/tuple
    - 0
    - -200
  push_to_git: false
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  time_between_retries: 10
  type: SwissArmyKnifeService
  vendor: ''
  waiting_time: 0
  yaql_query: ''
