- completed: 0
  creator: admin
  credentials: device
  custom_notification: false
  define_devices_from_payload: false
  description: Poll configuration and push to gitlab
  devices: []
  display_only_failed_nodes: true
  events: []
  failed: 0
  hidden: false
  jobs:
  - Start
  - End
  - poller_service
  - git_push_configurations
  last_modified: '2019-06-24 06:59:42.232902'
  mail_recipient: ''
  name: Configuration Management Workflow
  number_of_retries: 0
  number_of_targets: 0
  operating_system: ''
  pools: []
  positions: {}
  push_to_git: false
  query_property_type: ip_address
  send_notification: false
  send_notification_method: mail_feedback_notification
  time_between_retries: 10
  type: Workflow
  use_workflow_targets: false
  vendor: ''
  waiting_time: 0
  yaql_query: ''
