version: "3"
services:
  db:
    restart: always
    image: postgres:latest
    environment:
     - ENMS_DATABASE_URL=postgresql://enms:enms@db:5432/enms
    expose:
      - 5432
    networks:
      - db_network
  enms:
    restart: always
    environment:
     - ENMS_SECRET_KEY=docker
     - ENMS_CONFIG_MODE=Production
     - USE_VAULT=0
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - db_network
      - web_network
    depends_on:
      - db
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - enms
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
