- description: Configure BGP Peering with Napalm
  devices:
  - description: Washington
    id: 4
    ip_address: 192.168.105.5
    latitude: 38.89511
    location: Washington
    longitude: -77.03637
    model: Arista
    name: Washington
    operating_system: eos
    os_version: 15.5(3)M
    port: 22
    subtype: router
    vendor: Arista
  id: 3
  logs: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  name: napalm_configure_bgp_1
  number_of_retries: 0
  pools: []
  positions: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  state: Idle
  tasks: []
  time_between_retries: 10
  type: configure_bgp_service
  waiting_time: 0
- description: Create a VRF "test" with Netmiko
  devices:
  - description: Washington
    id: 4
    ip_address: 192.168.105.5
    latitude: 38.89511
    location: Washington
    longitude: -77.03637
    model: Arista
    name: Washington
    operating_system: eos
    os_version: 15.5(3)M
    port: 22
    subtype: router
    vendor: Arista
  id: 4
  logs: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  name: netmiko_create_vrf_test
  number_of_retries: 0
  pools: []
  positions: !!python/object/new:sqlalchemy.ext.mutable.MutableDict
    dictitems:
      Netmiko_VRF_workflow: &id001 !!python/tuple
      - 0
      - -150
    state:
      Netmiko_VRF_workflow: *id001
  state: Idle
  tasks: []
  time_between_retries: 10
  type: netmiko_configuration_service
  waiting_time: 0
- description: Check that the vrf "test" is configured
  devices:
  - description: Washington
    id: 4
    ip_address: 192.168.105.5
    latitude: 38.89511
    location: Washington
    longitude: -77.03637
    model: Arista
    name: Washington
    operating_system: eos
    os_version: 15.5(3)M
    port: 22
    subtype: router
    vendor: Arista
  id: 5
  logs: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  name: netmiko_check_vrf_test
  number_of_retries: 0
  pools: []
  positions: !!python/object/new:sqlalchemy.ext.mutable.MutableDict
    dictitems:
      Napalm_VRF_workflow: &id002 !!python/tuple
      - 0
      - -50
      Netmiko_VRF_workflow: &id003 !!python/tuple
      - 0
      - -50
    state:
      Napalm_VRF_workflow: *id002
      Netmiko_VRF_workflow: *id003
  state: Idle
  tasks: []
  time_between_retries: 10
  type: netmiko_validation_service
  waiting_time: 0
- description: Delete VRF "test"
  devices:
  - description: Washington
    id: 4
    ip_address: 192.168.105.5
    latitude: 38.89511
    location: Washington
    longitude: -77.03637
    model: Arista
    name: Washington
    operating_system: eos
    os_version: 15.5(3)M
    port: 22
    subtype: router
    vendor: Arista
  id: 6
  logs: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  name: netmiko_delete_vrf_test
  number_of_retries: 0
  pools: []
  positions: !!python/object/new:sqlalchemy.ext.mutable.MutableDict
    dictitems:
      Netmiko_VRF_workflow: &id004 !!python/tuple
      - 0
      - 50
    state:
      Netmiko_VRF_workflow: *id004
  state: Idle
  tasks: []
  time_between_retries: 10
  type: netmiko_configuration_service
  waiting_time: 1
- description: Check that the vrf "test" is NOT configured
  devices:
  - description: Washington
    id: 4
    ip_address: 192.168.105.5
    latitude: 38.89511
    location: Washington
    longitude: -77.03637
    model: Arista
    name: Washington
    operating_system: eos
    os_version: 15.5(3)M
    port: 22
    subtype: router
    vendor: Arista
  id: 7
  logs: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  name: netmiko_check_no_vrf_test
  number_of_retries: 0
  pools: []
  positions: !!python/object/new:sqlalchemy.ext.mutable.MutableDict
    dictitems:
      Napalm_VRF_workflow: &id005 !!python/tuple
      - 0
      - 150
      Netmiko_VRF_workflow: &id006 !!python/tuple
      - 0
      - 150
    state:
      Napalm_VRF_workflow: *id005
      Netmiko_VRF_workflow: *id006
  state: Idle
  tasks: []
  time_between_retries: 10
  type: netmiko_validation_service
  waiting_time: 0
- description: Create a VRF "test" with Napalm
  devices:
  - description: Washington
    id: 4
    ip_address: 192.168.105.5
    latitude: 38.89511
    location: Washington
    longitude: -77.03637
    model: Arista
    name: Washington
    operating_system: eos
    os_version: 15.5(3)M
    port: 22
    subtype: router
    vendor: Arista
  id: 9
  logs: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  name: napalm_create_vrf_test
  number_of_retries: 0
  pools: []
  positions: !!python/object/new:sqlalchemy.ext.mutable.MutableDict
    dictitems:
      Napalm_VRF_workflow: &id007 !!python/tuple
      - 0
      - -150
    state:
      Napalm_VRF_workflow: *id007
  state: Idle
  tasks: []
  time_between_retries: 10
  type: napalm_configuration_service
  waiting_time: 0
- description: Rollback a configuration with Napalm eos
  devices:
  - description: Washington
    id: 4
    ip_address: 192.168.105.5
    latitude: 38.89511
    location: Washington
    longitude: -77.03637
    model: Arista
    name: Washington
    operating_system: eos
    os_version: 15.5(3)M
    port: 22
    subtype: router
    vendor: Arista
  id: 10
  logs: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  name: Napalm eos Rollback
  number_of_retries: 0
  pools: []
  positions: !!python/object/new:sqlalchemy.ext.mutable.MutableDict
    dictitems:
      Napalm_VRF_workflow: &id008 !!python/tuple
      - 0
      - 50
    state:
      Napalm_VRF_workflow: *id008
  state: Idle
  tasks: []
  time_between_retries: 10
  type: napalm_rollback_service
  waiting_time: 0
- description: Use GET ReST call on Washington
  devices:
  - description: Washington
    id: 4
    ip_address: 192.168.105.5
    latitude: 38.89511
    location: Washington
    longitude: -77.03637
    model: Arista
    name: Washington
    operating_system: eos
    os_version: 15.5(3)M
    port: 22
    subtype: router
    vendor: Arista
  id: 12
  logs: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  name: GET_Washington
  number_of_retries: 0
  pools: []
  positions: !!python/object/new:sqlalchemy.ext.mutable.MutableDict
    dictitems:
      payload_transfer_workflow: &id009 !!python/tuple
      - -50
      - 0
    state:
      payload_transfer_workflow: *id009
  state: Idle
  tasks: []
  time_between_retries: 10
  type: rest_call_service
  waiting_time: 0
- description: 'Getter: get_facts'
  devices:
  - description: Washington
    id: 4
    ip_address: 192.168.105.5
    latitude: 38.89511
    location: Washington
    longitude: -77.03637
    model: Arista
    name: Washington
    operating_system: eos
    os_version: 15.5(3)M
    port: 22
    subtype: router
    vendor: Arista
  id: 13
  logs: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  name: get_facts
  number_of_retries: 0
  pools: []
  positions: !!python/object/new:sqlalchemy.ext.mutable.MutableDict
    dictitems:
      payload_transfer_workflow: &id010 !!python/tuple
      - -50
      - -100
    state:
      payload_transfer_workflow: *id010
  state: Idle
  tasks: []
  time_between_retries: 10
  type: napalm_getters_service
  waiting_time: 0
- description: 'Getter: get_interfaces'
  devices:
  - description: Washington
    id: 4
    ip_address: 192.168.105.5
    latitude: 38.89511
    location: Washington
    longitude: -77.03637
    model: Arista
    name: Washington
    operating_system: eos
    os_version: 15.5(3)M
    port: 22
    subtype: router
    vendor: Arista
  id: 14
  logs: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  name: get_interfaces
  number_of_retries: 0
  pools: []
  positions: !!python/object/new:sqlalchemy.ext.mutable.MutableDict
    dictitems:
      payload_transfer_workflow: &id011 !!python/tuple
      - 150
      - 100
    state:
      payload_transfer_workflow: *id011
  state: Idle
  tasks: []
  time_between_retries: 10
  type: napalm_getters_service
  waiting_time: 0
- description: 'Getter: get_interfaces_ip'
  devices:
  - description: Washington
    id: 4
    ip_address: 192.168.105.5
    latitude: 38.89511
    location: Washington
    longitude: -77.03637
    model: Arista
    name: Washington
    operating_system: eos
    os_version: 15.5(3)M
    port: 22
    subtype: router
    vendor: Arista
  id: 15
  logs: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  name: get_interfaces_ip
  number_of_retries: 0
  pools: []
  positions: !!python/object/new:sqlalchemy.ext.mutable.MutableDict
    dictitems:
      payload_transfer_workflow: &id012 !!python/tuple
      - 150
      - -100
    state:
      payload_transfer_workflow: *id012
  state: Idle
  tasks: []
  time_between_retries: 10
  type: napalm_getters_service
  waiting_time: 0
- description: 'Getter: get_config'
  devices:
  - description: Washington
    id: 4
    ip_address: 192.168.105.5
    latitude: 38.89511
    location: Washington
    longitude: -77.03637
    model: Arista
    name: Washington
    operating_system: eos
    os_version: 15.5(3)M
    port: 22
    subtype: router
    vendor: Arista
  id: 16
  logs: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  name: get_config
  number_of_retries: 0
  pools: []
  positions: !!python/object/new:sqlalchemy.ext.mutable.MutableDict
    dictitems:
      payload_transfer_workflow: &id013 !!python/tuple
      - 300
      - -100
    state:
      payload_transfer_workflow: *id013
  state: Idle
  tasks: []
  time_between_retries: 10
  type: napalm_getters_service
  waiting_time: 0
- description: Process Payload in example workflow
  devices:
  - description: Washington
    id: 4
    ip_address: 192.168.105.5
    latitude: 38.89511
    location: Washington
    longitude: -77.03637
    model: Arista
    name: Washington
    operating_system: eos
    os_version: 15.5(3)M
    port: 22
    subtype: router
    vendor: Arista
  id: 17
  logs: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  name: process_payload1
  number_of_retries: 0
  pools: []
  positions: !!python/object/new:sqlalchemy.ext.mutable.MutableDict
    dictitems:
      payload_transfer_workflow: &id014 !!python/tuple
      - 300
      - 0
    state:
      payload_transfer_workflow: *id014
  state: Idle
  tasks: []
  time_between_retries: 10
  type: swiss_army_knife_service
  waiting_time: 0
