- description: Create and delete a VRF with Netmiko
  destinations: []
  devices: []
  edges:
  - 1
  - 2
  - 3
  - 4
  - 5
  id: 8
  jobs:
  - 1
  - 2
  - 4
  - 5
  - 6
  - 7
  logs: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  multiprocessing: false
  name: Netmiko_VRF_workflow
  number_of_retries: 0
  operating_system: eos
  pools: []
  positions: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  sources: []
  state: Idle
  status: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  tasks: []
  time_between_retries: 10
  type: workflow
  vendor: Arista
  waiting_time: 0
- description: Create and delete a VRF with Napalm
  destinations: []
  devices: []
  edges:
  - 6
  - 7
  - 8
  - 9
  - 10
  id: 11
  jobs:
  - 1
  - 2
  - 9
  - 5
  - 10
  - 7
  logs: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  multiprocessing: false
  name: Napalm_VRF_workflow
  number_of_retries: 0
  operating_system: eos
  pools: []
  positions: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  sources: []
  state: Idle
  status: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  tasks: []
  time_between_retries: 10
  type: workflow
  vendor: Arista
  waiting_time: 0
- description: ReST call, Napalm getters, etc
  destinations: []
  devices: []
  edges:
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  id: 18
  jobs:
  - 1
  - 2
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  logs: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  multiprocessing: false
  name: payload_transfer_workflow
  number_of_retries: 0
  operating_system: eos
  pools: []
  positions: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  sources: []
  state: Idle
  status: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  tasks: []
  time_between_retries: 10
  type: workflow
  vendor: Arista
  waiting_time: 0
