- creator: 1
  credentials: device
  description: Create and delete a VRF with Netmiko
  devices: []
  edges:
  - 1
  - 2
  - 3
  - 4
  - 5
  id: 14
  jobs:
  - 1
  - 2
  - 10
  - 11
  - 12
  - 13
  multiprocessing: false
  name: Netmiko_VRF_workflow
  number_of_retries: 0
  operating_system: eos
  pools: []
  positions: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  send_notification: false
  send_notification_method: mail_feedback_notification
  time_between_retries: 10
  type: Workflow
  vendor: Arista
  waiting_time: 0
- creator: 1
  credentials: device
  description: Create and delete a VRF with Napalm
  devices: []
  edges:
  - 6
  - 7
  - 8
  - 9
  - 10
  id: 17
  jobs:
  - 1
  - 2
  - 15
  - 11
  - 16
  - 13
  multiprocessing: false
  name: Napalm_VRF_workflow
  number_of_retries: 0
  operating_system: eos
  pools: []
  positions: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  send_notification: false
  send_notification_method: mail_feedback_notification
  time_between_retries: 10
  type: Workflow
  vendor: Arista
  waiting_time: 0
- creator: 1
  credentials: device
  description: ReST call, Napalm getters, etc
  devices: []
  edges:
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  id: 24
  jobs:
  - 1
  - 2
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23
  multiprocessing: false
  name: payload_transfer_workflow
  number_of_retries: 0
  operating_system: eos
  pools: []
  positions: !!python/object:sqlalchemy.ext.mutable.MutableDict {}
  send_notification: false
  send_notification_method: mail_feedback_notification
  time_between_retries: 10
  type: Workflow
  vendor: Arista
  waiting_time: 0
