completed: 0
creator: admin
credentials: device
description: Push configurations to Gitlab
devices: []
display_only_failed_nodes: true
events: []
failed: 0
has_targets: false
hidden: false
last_modified: '2019-06-02 19:54:52.390609'
mail_recipient: ''
max_processes: 5
multiprocessing: false
name: git_push_configurations
number_of_retries: 0
number_of_targets: 0
operating_system: ''
pools: []
positions:
  A: !!python/tuple
  - -88
  - -108
  Configuration Management Workflow: !!python/tuple
  - 0
  - 300
push_to_git: false
send_notification: false
send_notification_method: mail_feedback_notification
time_between_retries: 10
type: SwissArmyKnifeService
vendor: ''
waiting_time: 0
