---
- name: EOS Show Commands
  hosts: all
  gather_facts: false
  connection: local

  vars:
    cli:
      host: "192.168.105.5"
      username: "admin"
      password: "admin"
      authorize: true
      transport: cli

  tasks:
    - name: eos show commands
      eos_command:
        commands:
          - show version
        provider: "{{ cli }}"
      register: output

    - name: show output
      debug:
        var: output